// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package agentprotocol



type AgentError struct {
	// Code corresponds to the JSON schema field "code".
	Code ErrorCode `json:"code"`

	// Details corresponds to the JSON schema field "details".
	Details AgentErrorDetails `json:"details,omitempty,omitzero"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// Retryable corresponds to the JSON schema field "retryable".
	Retryable bool `json:"retryable"`
}

type AgentErrorDetails map[string]interface{}

type AgentScope struct {
	// Domains corresponds to the JSON schema field "domains".
	Domains []string `json:"domains"`

	// EntityIds corresponds to the JSON schema field "entityIds".
	EntityIds []string `json:"entityIds,omitempty,omitzero"`

	// From corresponds to the JSON schema field "from".
	From *string `json:"from,omitempty,omitzero"`

	// To corresponds to the JSON schema field "to".
	To *string `json:"to,omitempty,omitzero"`
}

type Budget struct {
	// MaxConcurrency corresponds to the JSON schema field "maxConcurrency".
	MaxConcurrency int `json:"maxConcurrency"`

	// MaxDurationMs corresponds to the JSON schema field "maxDurationMs".
	MaxDurationMs int `json:"maxDurationMs"`

	// MaxRepeatedToolCalls corresponds to the JSON schema field
	// "maxRepeatedToolCalls".
	MaxRepeatedToolCalls int `json:"maxRepeatedToolCalls"`

	// MaxSteps corresponds to the JSON schema field "maxSteps".
	MaxSteps int `json:"maxSteps"`

	// MaxTokens corresponds to the JSON schema field "maxTokens".
	MaxTokens int `json:"maxTokens"`

	// MaxWorkers corresponds to the JSON schema field "maxWorkers".
	MaxWorkers int `json:"maxWorkers"`
}

type CalendarCursor string

type CalendarReadData struct {
	// Events corresponds to the JSON schema field "events".
	Events []CalendarReadDataEventsElem `json:"events"`

	// HasMore corresponds to the JSON schema field "hasMore".
	HasMore bool `json:"hasMore"`

	// NextCursor corresponds to the JSON schema field "nextCursor".
	NextCursor CalendarReadDataNextCursor `json:"nextCursor"`

	// Window corresponds to the JSON schema field "window".
	Window CalendarReadDataWindow `json:"window"`
}

type CalendarReadDataEventsElem struct {
	// EndAt corresponds to the JSON schema field "endAt".
	EndAt DateTime `json:"endAt"`

	// ID corresponds to the JSON schema field "id".
	ID UUID `json:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind"`

	// StartAt corresponds to the JSON schema field "startAt".
	StartAt DateTime `json:"startAt"`

	// Timezone corresponds to the JSON schema field "timezone".
	Timezone string `json:"timezone"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`

	// Version corresponds to the JSON schema field "version".
	Version int `json:"version"`
}

type CalendarReadDataNextCursor *string

type CalendarReadDataWindow struct {
	// End corresponds to the JSON schema field "end".
	End DateTime `json:"end"`

	// Start corresponds to the JSON schema field "start".
	Start DateTime `json:"start"`
}

type CalendarReadInput struct {
	// Cursor corresponds to the JSON schema field "cursor".
	Cursor *CalendarCursor `json:"cursor,omitempty,omitzero"`

	// End corresponds to the JSON schema field "end".
	End DateTime `json:"end"`

	// Limit corresponds to the JSON schema field "limit".
	Limit int `json:"limit,omitempty,omitzero"`

	// Start corresponds to the JSON schema field "start".
	Start DateTime `json:"start"`
}

type CalendarReadRequest struct {
	// CallID corresponds to the JSON schema field "callId".
	CallID string `json:"callId"`

	// Input corresponds to the JSON schema field "input".
	Input CalendarReadInput `json:"input"`
}

type CapabilitySnapshot struct {
	// ExecutionMode corresponds to the JSON schema field "executionMode".
	ExecutionMode ExecutionMode `json:"executionMode"`

	// RuntimeVersion corresponds to the JSON schema field "runtimeVersion".
	RuntimeVersion string `json:"runtimeVersion"`

	// Scope corresponds to the JSON schema field "scope".
	Scope AgentScope `json:"scope"`

	// Skills corresponds to the JSON schema field "skills".
	Skills []SkillRef `json:"skills"`

	// ToolIds corresponds to the JSON schema field "toolIds".
	ToolIds []string `json:"toolIds"`
}

type ConformanceCase struct {
	// ExpectedTransitions corresponds to the JSON schema field "expectedTransitions".
	ExpectedTransitions []RuntimeTransition `json:"expectedTransitions"`

	// InitialState corresponds to the JSON schema field "initialState".
	InitialState RuntimeState `json:"initialState"`

	// Inputs corresponds to the JSON schema field "inputs".
	Inputs []RuntimeInput `json:"inputs"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// ProtocolVersion corresponds to the JSON schema field "protocolVersion".
	ProtocolVersion string `json:"protocolVersion"`
}

type ContentBlock struct {
	// Text corresponds to the JSON schema field "text".
	Text *string `json:"text,omitempty,omitzero"`

	// ToolCall corresponds to the JSON schema field "toolCall".
	ToolCall *ToolCall `json:"toolCall,omitempty,omitzero"`

	// ToolResult corresponds to the JSON schema field "toolResult".
	ToolResult *ToolResult `json:"toolResult,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type ContentBlockType `json:"type"`
}

type ContentBlockType string

const ContentBlockTypeText ContentBlockType = "text"
const ContentBlockTypeToolCall ContentBlockType = "tool_call"
const ContentBlockTypeToolResult ContentBlockType = "tool_result"

type DateTime string

type ErrorCode string

const ErrorCodeApprovalDenied ErrorCode = "approval_denied"
const ErrorCodeCancelled ErrorCode = "cancelled"
const ErrorCodeCapabilityUnavailable ErrorCode = "capability_unavailable"
const ErrorCodeInternalError ErrorCode = "internal_error"
const ErrorCodePermissionDenied ErrorCode = "permission_denied"
const ErrorCodeProtocolIncompatible ErrorCode = "protocol_incompatible"
const ErrorCodeProviderRateLimited ErrorCode = "provider_rate_limited"
const ErrorCodeProviderUnavailable ErrorCode = "provider_unavailable"
const ErrorCodeTimeout ErrorCode = "timeout"
const ErrorCodeToolFailed ErrorCode = "tool_failed"
const ErrorCodeValidationFailed ErrorCode = "validation_failed"
const ErrorCodeVersionConflict ErrorCode = "version_conflict"

type ExecutionMode string

const ExecutionModeBackground ExecutionMode = "background"
const ExecutionModeForeground ExecutionMode = "foreground"

type Message struct {
	// Content corresponds to the JSON schema field "content".
	Content []ContentBlock `json:"content"`

	// Role corresponds to the JSON schema field "role".
	Role MessageRole `json:"role"`
}

type MessageRole string

const MessageRoleAssistant MessageRole = "assistant"
const MessageRoleSystem MessageRole = "system"
const MessageRoleTool MessageRole = "tool"
const MessageRoleUser MessageRole = "user"

type ModelTurnRequest struct {
	// Messages corresponds to the JSON schema field "messages".
	Messages []Message `json:"messages"`

	// ModelProfile corresponds to the JSON schema field "modelProfile".
	ModelProfile string `json:"modelProfile"`

	// ProtocolVersion corresponds to the JSON schema field "protocolVersion".
	ProtocolVersion string `json:"protocolVersion"`

	// RunID corresponds to the JSON schema field "runId".
	RunID string `json:"runId"`

	// Tools corresponds to the JSON schema field "tools".
	Tools []ToolSpec `json:"tools"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID string `json:"turnId"`
}

type ProviderEnvelope struct {
	// Event corresponds to the JSON schema field "event".
	Event ProviderEvent `json:"event"`

	// ProtocolVersion corresponds to the JSON schema field "protocolVersion".
	ProtocolVersion interface{} `json:"protocolVersion"`

	// RunID corresponds to the JSON schema field "runId".
	RunID string `json:"runId"`

	// Sequence corresponds to the JSON schema field "sequence".
	Sequence int `json:"sequence"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID string `json:"turnId"`
}

type ProviderEvent struct {
	// Call corresponds to the JSON schema field "call".
	Call *ToolCall `json:"call,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *AgentError `json:"error,omitempty,omitzero"`

	// StopReason corresponds to the JSON schema field "stopReason".
	StopReason *ProviderEventStopReason `json:"stopReason,omitempty,omitzero"`

	// Text corresponds to the JSON schema field "text".
	Text *string `json:"text,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type ProviderEventType `json:"type"`

	// Usage corresponds to the JSON schema field "usage".
	Usage *Usage `json:"usage,omitempty,omitzero"`
}

type ProviderEventStopReason string

const ProviderEventStopReasonCancelled ProviderEventStopReason = "cancelled"
const ProviderEventStopReasonEndTurn ProviderEventStopReason = "end_turn"
const ProviderEventStopReasonMaxTokens ProviderEventStopReason = "max_tokens"
const ProviderEventStopReasonToolUse ProviderEventStopReason = "tool_use"

type ProviderEventType string

const ProviderEventTypeCompleted ProviderEventType = "completed"
const ProviderEventTypeError ProviderEventType = "error"
const ProviderEventTypeTextDelta ProviderEventType = "text_delta"
const ProviderEventTypeToolCall ProviderEventType = "tool_call"

type ReadonlyRunFinish struct {
	// Error corresponds to the JSON schema field "error".
	Error *AgentError `json:"error,omitempty,omitzero"`

	// Phase corresponds to the JSON schema field "phase".
	Phase ReadonlyRunFinishPhase `json:"phase"`

	// Steps corresponds to the JSON schema field "steps".
	Steps []ReadonlyRunFinishStepsElem `json:"steps"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary"`
}

type ReadonlyRunFinishPhase string

const ReadonlyRunFinishPhaseCancelled ReadonlyRunFinishPhase = "cancelled"
const ReadonlyRunFinishPhaseCompleted ReadonlyRunFinishPhase = "completed"
const ReadonlyRunFinishPhaseFailed ReadonlyRunFinishPhase = "failed"

type ReadonlyRunFinishStepsElem struct {
	// Detail corresponds to the JSON schema field "detail".
	Detail string `json:"detail"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`
}

type ReadonlyRunStart struct {
	// ExecutionMode corresponds to the JSON schema field "executionMode".
	ExecutionMode ExecutionMode `json:"executionMode"`

	// Intent corresponds to the JSON schema field "intent".
	Intent string `json:"intent"`

	// ModelProfile corresponds to the JSON schema field "modelProfile".
	ModelProfile string `json:"modelProfile"`

	// Scope corresponds to the JSON schema field "scope".
	Scope AgentScope `json:"scope"`

	// Timezone corresponds to the JSON schema field "timezone".
	Timezone string `json:"timezone"`
}

type ReadonlyRunView struct {
	// Budget corresponds to the JSON schema field "budget".
	Budget Budget `json:"budget"`

	// CapabilitySnapshot corresponds to the JSON schema field "capabilitySnapshot".
	CapabilitySnapshot CapabilitySnapshot `json:"capabilitySnapshot"`

	// DeadlineAt corresponds to the JSON schema field "deadlineAt".
	DeadlineAt DateTime `json:"deadlineAt"`

	// Error corresponds to the JSON schema field "error".
	Error *AgentError `json:"error,omitempty,omitzero"`

	// ExecutionMode corresponds to the JSON schema field "executionMode".
	ExecutionMode ExecutionMode `json:"executionMode"`

	// ModelProfile corresponds to the JSON schema field "modelProfile".
	ModelProfile string `json:"modelProfile"`

	// ProtocolVersion corresponds to the JSON schema field "protocolVersion".
	ProtocolVersion string `json:"protocolVersion"`

	// ResultOrigin corresponds to the JSON schema field "resultOrigin".
	ResultOrigin ReadonlyRunViewResultOrigin `json:"resultOrigin"`

	// RunID corresponds to the JSON schema field "runId".
	RunID UUID `json:"runId"`

	// ServerNow corresponds to the JSON schema field "serverNow".
	ServerNow DateTime `json:"serverNow"`

	// Status corresponds to the JSON schema field "status".
	Status ReadonlyRunViewStatus `json:"status"`

	// Summary corresponds to the JSON schema field "summary".
	Summary *string `json:"summary,omitempty,omitzero"`

	// Usage corresponds to the JSON schema field "usage".
	Usage Usage `json:"usage"`

	// UsageComplete corresponds to the JSON schema field "usageComplete".
	UsageComplete bool `json:"usageComplete"`

	// Version corresponds to the JSON schema field "version".
	Version int `json:"version"`
}

type ReadonlyRunViewResultOrigin string

const ReadonlyRunViewResultOriginClientReported ReadonlyRunViewResultOrigin = "client_reported"
const ReadonlyRunViewResultOriginServerRuntime ReadonlyRunViewResultOrigin = "server_runtime"

type ReadonlyRunViewStatus string

const ReadonlyRunViewStatusAnalyzing ReadonlyRunViewStatus = "analyzing"
const ReadonlyRunViewStatusCompleted ReadonlyRunViewStatus = "completed"
const ReadonlyRunViewStatusFailed ReadonlyRunViewStatus = "failed"
const ReadonlyRunViewStatusReady ReadonlyRunViewStatus = "ready"
const ReadonlyRunViewStatusStopped ReadonlyRunViewStatus = "stopped"

type RuntimeEffect struct {
	// ApprovalID corresponds to the JSON schema field "approvalId".
	ApprovalID *string `json:"approvalId,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *AgentError `json:"error,omitempty,omitzero"`

	// Text corresponds to the JSON schema field "text".
	Text *string `json:"text,omitempty,omitzero"`

	// ToolCall corresponds to the JSON schema field "toolCall".
	ToolCall *ToolCall `json:"toolCall,omitempty,omitzero"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID *string `json:"turnId,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type RuntimeEffectType `json:"type"`
}

type RuntimeEffectType string

const RuntimeEffectTypeCancelRun RuntimeEffectType = "cancel_run"
const RuntimeEffectTypeCompleteRun RuntimeEffectType = "complete_run"
const RuntimeEffectTypeEmitText RuntimeEffectType = "emit_text"
const RuntimeEffectTypeExecuteTool RuntimeEffectType = "execute_tool"
const RuntimeEffectTypeFailRun RuntimeEffectType = "fail_run"
const RuntimeEffectTypeRequestApproval RuntimeEffectType = "request_approval"
const RuntimeEffectTypeRequestModelTurn RuntimeEffectType = "request_model_turn"
const RuntimeEffectTypeResolveTool RuntimeEffectType = "resolve_tool"

type RuntimeInput struct {
	// ApprovalResponse corresponds to the JSON schema field "approvalResponse".
	ApprovalResponse *RuntimeInputApprovalResponse `json:"approvalResponse,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *AgentError `json:"error,omitempty,omitzero"`

	// ProviderEvent corresponds to the JSON schema field "providerEvent".
	ProviderEvent *ProviderEvent `json:"providerEvent,omitempty,omitzero"`

	// Reason corresponds to the JSON schema field "reason".
	Reason *string `json:"reason,omitempty,omitzero"`

	// Text corresponds to the JSON schema field "text".
	Text *string `json:"text,omitempty,omitzero"`

	// ToolResolution corresponds to the JSON schema field "toolResolution".
	ToolResolution *ToolResolution `json:"toolResolution,omitempty,omitzero"`

	// ToolResult corresponds to the JSON schema field "toolResult".
	ToolResult *RuntimeInputToolResult `json:"toolResult,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type RuntimeInputType `json:"type"`
}

type RuntimeInputApprovalResponse struct {
	// ApprovalID corresponds to the JSON schema field "approvalId".
	ApprovalID string `json:"approvalId"`

	// Decision corresponds to the JSON schema field "decision".
	Decision RuntimeInputApprovalResponseDecision `json:"decision"`
}

type RuntimeInputApprovalResponseDecision string

const RuntimeInputApprovalResponseDecisionAllow RuntimeInputApprovalResponseDecision = "allow"
const RuntimeInputApprovalResponseDecisionDeny RuntimeInputApprovalResponseDecision = "deny"

type RuntimeInputToolResult struct {
	// CallID corresponds to the JSON schema field "callId".
	CallID string `json:"callId"`

	// Result corresponds to the JSON schema field "result".
	Result ToolResult `json:"result"`
}

type RuntimeInputType string

const RuntimeInputTypeApprovalResponse RuntimeInputType = "approval_response"
const RuntimeInputTypeCancel RuntimeInputType = "cancel"
const RuntimeInputTypeProviderEvent RuntimeInputType = "provider_event"
const RuntimeInputTypeRuntimeError RuntimeInputType = "runtime_error"
const RuntimeInputTypeToolResolution RuntimeInputType = "tool_resolution"
const RuntimeInputTypeToolResult RuntimeInputType = "tool_result"
const RuntimeInputTypeUserMessage RuntimeInputType = "user_message"

type RuntimePhase string

const RuntimePhaseApprovalPending RuntimePhase = "approval_pending"
const RuntimePhaseCancelled RuntimePhase = "cancelled"
const RuntimePhaseCompleted RuntimePhase = "completed"
const RuntimePhaseFailed RuntimePhase = "failed"
const RuntimePhaseIdle RuntimePhase = "idle"
const RuntimePhaseModelPending RuntimePhase = "model_pending"
const RuntimePhaseModelStreaming RuntimePhase = "model_streaming"
const RuntimePhaseToolPending RuntimePhase = "tool_pending"

type RuntimeState struct {
	// AssistantDraft corresponds to the JSON schema field "assistantDraft".
	AssistantDraft *string `json:"assistantDraft,omitempty,omitzero"`

	// Budget corresponds to the JSON schema field "budget".
	Budget Budget `json:"budget"`

	// CapabilitySnapshot corresponds to the JSON schema field "capabilitySnapshot".
	CapabilitySnapshot CapabilitySnapshot `json:"capabilitySnapshot"`

	// Error corresponds to the JSON schema field "error".
	Error *AgentError `json:"error,omitempty,omitzero"`

	// ExecutionMode corresponds to the JSON schema field "executionMode".
	ExecutionMode ExecutionMode `json:"executionMode"`

	// LastToolFingerprint corresponds to the JSON schema field "lastToolFingerprint".
	LastToolFingerprint *string `json:"lastToolFingerprint,omitempty,omitzero"`

	// Messages corresponds to the JSON schema field "messages".
	Messages []Message `json:"messages"`

	// PendingApprovalID corresponds to the JSON schema field "pendingApprovalId".
	PendingApprovalID *string `json:"pendingApprovalId,omitempty,omitzero"`

	// PendingToolCall corresponds to the JSON schema field "pendingToolCall".
	PendingToolCall *ToolCall `json:"pendingToolCall,omitempty,omitzero"`

	// Phase corresponds to the JSON schema field "phase".
	Phase RuntimePhase `json:"phase"`

	// ProtocolVersion corresponds to the JSON schema field "protocolVersion".
	ProtocolVersion string `json:"protocolVersion"`

	// RepeatedToolCalls corresponds to the JSON schema field "repeatedToolCalls".
	RepeatedToolCalls int `json:"repeatedToolCalls"`

	// RunID corresponds to the JSON schema field "runId".
	RunID string `json:"runId"`

	// Sequence corresponds to the JSON schema field "sequence".
	Sequence int `json:"sequence"`

	// StepCount corresponds to the JSON schema field "stepCount".
	StepCount int `json:"stepCount"`

	// Usage corresponds to the JSON schema field "usage".
	Usage Usage `json:"usage"`
}

type RuntimeTransition struct {
	// Effects corresponds to the JSON schema field "effects".
	Effects []RuntimeEffect `json:"effects"`

	// State corresponds to the JSON schema field "state".
	State RuntimeState `json:"state"`
}

type SemVer string

type SideEffect string

const SideEffectExternalCommunication SideEffect = "external_communication"
const SideEffectIrreversibleWrite SideEffect = "irreversible_write"
const SideEffectRead SideEffect = "read"
const SideEffectReversibleWrite SideEffect = "reversible_write"

type SkillActivation struct {
	// ActiveToolIds corresponds to the JSON schema field "activeToolIds".
	ActiveToolIds []string `json:"activeToolIds"`

	// Instructions corresponds to the JSON schema field "instructions".
	Instructions string `json:"instructions"`

	// RequestedToolIds corresponds to the JSON schema field "requestedToolIds".
	RequestedToolIds []string `json:"requestedToolIds"`

	// Skill corresponds to the JSON schema field "skill".
	Skill SkillRef `json:"skill"`

	// SupportingFiles corresponds to the JSON schema field "supportingFiles".
	SupportingFiles []SupportingFileDescriptor `json:"supportingFiles"`
}

type SkillDescriptor struct {
	// BackgroundAllowed corresponds to the JSON schema field "backgroundAllowed".
	BackgroundAllowed bool `json:"backgroundAllowed"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// Digest corresponds to the JSON schema field "digest".
	Digest string `json:"digest"`

	// DisableModelInvocation corresponds to the JSON schema field
	// "disableModelInvocation".
	DisableModelInvocation bool `json:"disableModelInvocation"`

	// ExecutionTarget corresponds to the JSON schema field "executionTarget".
	ExecutionTarget SkillDescriptorExecutionTarget `json:"executionTarget"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// RiskLevel corresponds to the JSON schema field "riskLevel".
	RiskLevel SkillDescriptorRiskLevel `json:"riskLevel"`

	// Scope corresponds to the JSON schema field "scope".
	Scope SkillDescriptorScope `json:"scope"`

	// UserInvocable corresponds to the JSON schema field "userInvocable".
	UserInvocable bool `json:"userInvocable"`

	// Version corresponds to the JSON schema field "version".
	Version SemVer `json:"version"`
}

type SkillDescriptorExecutionTarget string

const SkillDescriptorExecutionTargetClient SkillDescriptorExecutionTarget = "client"
const SkillDescriptorExecutionTargetEither SkillDescriptorExecutionTarget = "either"
const SkillDescriptorExecutionTargetServer SkillDescriptorExecutionTarget = "server"

type SkillDescriptorRiskLevel string

const SkillDescriptorRiskLevelCritical SkillDescriptorRiskLevel = "critical"
const SkillDescriptorRiskLevelHigh SkillDescriptorRiskLevel = "high"
const SkillDescriptorRiskLevelLow SkillDescriptorRiskLevel = "low"
const SkillDescriptorRiskLevelMedium SkillDescriptorRiskLevel = "medium"

type SkillDescriptorScope string

const SkillDescriptorScopeDevice SkillDescriptorScope = "device"
const SkillDescriptorScopeSystem SkillDescriptorScope = "system"
const SkillDescriptorScopeUser SkillDescriptorScope = "user"

type SkillManifest struct {
	// AllowedTools corresponds to the JSON schema field "allowed-tools".
	AllowedTools []string `json:"allowed-tools"`

	// BackgroundAllowed corresponds to the JSON schema field "background-allowed".
	BackgroundAllowed bool `json:"background-allowed"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// DisableModelInvocation corresponds to the JSON schema field
	// "disable-model-invocation".
	DisableModelInvocation bool `json:"disable-model-invocation"`

	// ExecutionTarget corresponds to the JSON schema field "execution-target".
	ExecutionTarget SkillManifestExecutionTarget `json:"execution-target"`

	// MinRuntimeVersion corresponds to the JSON schema field "min-runtime-version".
	MinRuntimeVersion SemVer `json:"min-runtime-version"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// RiskLevel corresponds to the JSON schema field "risk-level".
	RiskLevel SkillManifestRiskLevel `json:"risk-level"`

	// UserInvocable corresponds to the JSON schema field "user-invocable".
	UserInvocable bool `json:"user-invocable"`

	// Version corresponds to the JSON schema field "version".
	Version SemVer `json:"version"`
}

type SkillManifestExecutionTarget string

const SkillManifestExecutionTargetClient SkillManifestExecutionTarget = "client"
const SkillManifestExecutionTargetEither SkillManifestExecutionTarget = "either"
const SkillManifestExecutionTargetServer SkillManifestExecutionTarget = "server"

type SkillManifestRiskLevel string

const SkillManifestRiskLevelCritical SkillManifestRiskLevel = "critical"
const SkillManifestRiskLevelHigh SkillManifestRiskLevel = "high"
const SkillManifestRiskLevelLow SkillManifestRiskLevel = "low"
const SkillManifestRiskLevelMedium SkillManifestRiskLevel = "medium"

type SkillRef struct {
	// Digest corresponds to the JSON schema field "digest".
	Digest string `json:"digest"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Version corresponds to the JSON schema field "version".
	Version SemVer `json:"version"`
}

type SupportingFileDescriptor struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind SupportingFileDescriptorKind `json:"kind"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Size corresponds to the JSON schema field "size".
	Size int `json:"size"`
}

type SupportingFileDescriptorKind string

const SupportingFileDescriptorKindAsset SupportingFileDescriptorKind = "asset"
const SupportingFileDescriptorKindReference SupportingFileDescriptorKind = "reference"
const SupportingFileDescriptorKindSchema SupportingFileDescriptorKind = "schema"

type ToolCall struct {
	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Input corresponds to the JSON schema field "input".
	Input ToolCallInput `json:"input"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

type ToolCallInput map[string]interface{}

type ToolResolution struct {
	// ApprovalID corresponds to the JSON schema field "approvalId".
	ApprovalID *string `json:"approvalId,omitempty,omitzero"`

	// CallID corresponds to the JSON schema field "callId".
	CallID string `json:"callId"`

	// Decision corresponds to the JSON schema field "decision".
	Decision ToolResolutionDecision `json:"decision"`

	// Error corresponds to the JSON schema field "error".
	Error *AgentError `json:"error,omitempty,omitzero"`
}

type ToolResolutionDecision string

const ToolResolutionDecisionApproval ToolResolutionDecision = "approval"
const ToolResolutionDecisionDenied ToolResolutionDecision = "denied"
const ToolResolutionDecisionExecute ToolResolutionDecision = "execute"
const ToolResolutionDecisionUnavailable ToolResolutionDecision = "unavailable"

type ToolResult struct {
	// Data corresponds to the JSON schema field "data".
	Data ToolResultData `json:"data,omitempty,omitzero"`

	// Display corresponds to the JSON schema field "display".
	Display *string `json:"display,omitempty,omitzero"`

	// Error corresponds to the JSON schema field "error".
	Error *AgentError `json:"error,omitempty,omitzero"`

	// Ok corresponds to the JSON schema field "ok".
	Ok bool `json:"ok"`
}

type ToolResultData map[string]interface{}

type ToolSpec struct {
	// ApprovalPolicy corresponds to the JSON schema field "approvalPolicy".
	ApprovalPolicy ToolSpecApprovalPolicy `json:"approvalPolicy"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description"`

	// ExecutionTargets corresponds to the JSON schema field "executionTargets".
	ExecutionTargets []ToolSpecExecutionTargetsElem `json:"executionTargets"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Idempotent corresponds to the JSON schema field "idempotent".
	Idempotent bool `json:"idempotent"`

	// InputSchema corresponds to the JSON schema field "inputSchema".
	InputSchema ToolSpecInputSchema `json:"inputSchema"`

	// OutputSchema corresponds to the JSON schema field "outputSchema".
	OutputSchema ToolSpecOutputSchema `json:"outputSchema"`

	// RequiredDomains corresponds to the JSON schema field "requiredDomains".
	RequiredDomains []string `json:"requiredDomains"`

	// ResultMaxBytes corresponds to the JSON schema field "resultMaxBytes".
	ResultMaxBytes int `json:"resultMaxBytes"`

	// SideEffect corresponds to the JSON schema field "sideEffect".
	SideEffect SideEffect `json:"sideEffect"`

	// TimeoutMs corresponds to the JSON schema field "timeoutMs".
	TimeoutMs int `json:"timeoutMs"`
}

type ToolSpecApprovalPolicy string

const ToolSpecApprovalPolicyAlways ToolSpecApprovalPolicy = "always"
const ToolSpecApprovalPolicyIfNeeded ToolSpecApprovalPolicy = "if_needed"
const ToolSpecApprovalPolicyNever ToolSpecApprovalPolicy = "never"

type ToolSpecExecutionTargetsElem string

const ToolSpecExecutionTargetsElemClient ToolSpecExecutionTargetsElem = "client"
const ToolSpecExecutionTargetsElemServer ToolSpecExecutionTargetsElem = "server"

type ToolSpecInputSchema map[string]interface{}

type ToolSpecOutputSchema map[string]interface{}

type UUID string

type Usage struct {
	// InputTokens corresponds to the JSON schema field "inputTokens".
	InputTokens int `json:"inputTokens"`

	// OutputTokens corresponds to the JSON schema field "outputTokens".
	OutputTokens int `json:"outputTokens"`

	// TotalTokens corresponds to the JSON schema field "totalTokens".
	TotalTokens int `json:"totalTokens"`
}

type WorkerOutputContract struct {
	// Sections corresponds to the JSON schema field "sections".
	Sections [4]WorkerOutputContractSectionsElem `json:"sections"`
}

type WorkerOutputContractSectionsElem string

const WorkerOutputContractSectionsElemFindings WorkerOutputContractSectionsElem = "findings"
const WorkerOutputContractSectionsElemNextSteps WorkerOutputContractSectionsElem = "next_steps"
const WorkerOutputContractSectionsElemRisks WorkerOutputContractSectionsElem = "risks"
const WorkerOutputContractSectionsElemSummary WorkerOutputContractSectionsElem = "summary"

type WorkerResult struct {
	// Error corresponds to the JSON schema field "error".
	Error *AgentError `json:"error,omitempty,omitzero"`

	// ProtocolVersion corresponds to the JSON schema field "protocolVersion".
	ProtocolVersion string `json:"protocolVersion"`

	// Sections corresponds to the JSON schema field "sections".
	Sections *WorkerResultSections `json:"sections,omitempty,omitzero"`

	// State corresponds to the JSON schema field "state".
	State WorkerResultState `json:"state"`

	// Usage corresponds to the JSON schema field "usage".
	Usage Usage `json:"usage"`

	// WorkerID corresponds to the JSON schema field "workerId".
	WorkerID string `json:"workerId"`
}

type WorkerResultSections struct {
	// Findings corresponds to the JSON schema field "findings".
	Findings string `json:"findings"`

	// NextSteps corresponds to the JSON schema field "next_steps".
	NextSteps string `json:"next_steps"`

	// Risks corresponds to the JSON schema field "risks".
	Risks string `json:"risks"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary"`
}

type WorkerResultState string

const WorkerResultStateCancelled WorkerResultState = "cancelled"
const WorkerResultStateFailed WorkerResultState = "failed"
const WorkerResultStateSucceeded WorkerResultState = "succeeded"

type WorkerSkillInstructions struct {
	// Instructions corresponds to the JSON schema field "instructions".
	Instructions string `json:"instructions"`

	// Skill corresponds to the JSON schema field "skill".
	Skill SkillRef `json:"skill"`
}

type WorkerSpawnSpec struct {
	// Budget corresponds to the JSON schema field "budget".
	Budget Budget `json:"budget"`

	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities CapabilitySnapshot `json:"capabilities"`

	// Depth corresponds to the JSON schema field "depth".
	Depth int `json:"depth"`

	// ExecutionMode corresponds to the JSON schema field "executionMode".
	ExecutionMode ExecutionMode `json:"executionMode"`

	// OutputContract corresponds to the JSON schema field "outputContract".
	OutputContract WorkerOutputContract `json:"outputContract"`

	// ParentRunID corresponds to the JSON schema field "parentRunId".
	ParentRunID string `json:"parentRunId"`

	// ProtocolVersion corresponds to the JSON schema field "protocolVersion".
	ProtocolVersion string `json:"protocolVersion"`

	// SkillInstructions corresponds to the JSON schema field "skillInstructions".
	SkillInstructions []WorkerSkillInstructions `json:"skillInstructions"`

	// Task corresponds to the JSON schema field "task".
	Task WorkerTask `json:"task"`

	// WorkerID corresponds to the JSON schema field "workerId".
	WorkerID string `json:"workerId"`
}

type WorkerTask struct {
	// Constraints corresponds to the JSON schema field "constraints".
	Constraints []string `json:"constraints"`

	// Goal corresponds to the JSON schema field "goal".
	Goal string `json:"goal"`

	// Hints corresponds to the JSON schema field "hints".
	Hints []string `json:"hints"`

	// Scope corresponds to the JSON schema field "scope".
	Scope []string `json:"scope"`

	// SuccessCriteria corresponds to the JSON schema field "successCriteria".
	SuccessCriteria []string `json:"successCriteria"`
}
